### ISSUE TITLE
Program does not exit with error code, when encountering error

### ISSUE THREAD

**Issue by mariuswilms** [atelierdisko/css-nextgen#1]
We're using the program as part of a build script (`build.sh`) with `set -o errexit`. Given a CSS file with the following contents (a minimum reproduciable example) the command fails with a `ParseError`. But the build script continues execution. I expected the script to stop. 

```CSS
.shop-view__product-option {
  padding-bottom: calc(3px * var(--base-spacing-unit));
  display: grid;
  grid-template-columns: 1fr 1fr;
  grid-template-areas: "title button-empty" "price button-empty";
  grid-row-gap: calc(0.5px * var(--base-spacing-unit)-5px);
}
```

My suspicion: css-nextgen does not set the correct retval when exiting.
